name: ""
title: Sebastiao Ribeiro
tagline: Software Engineer
url: "https://sebastiao.me"
remote_theme: pages-themes/hacker
author: Sebastiao Ribeiro
github:
  is_project_page: false
locale: en_US
social:
  name: Sebastiao Ribeiro
  links:
    - https://www.linkedin.com/in/sebasrib
    - https://github.com/sebasrib
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
