name: ""
title: Sebastiao Ribeiro
tagline: Software Engineer
url: "https://sebastiao.me"
remote_theme: pages-themes/hacker
author: Sebastiao Ribeiro
locale: en_US
google_site_verification: XXXXXXXXXXXXXXX
social:
  name: Sebastiao Ribeiro
  links:
    - https://www.linkedin.com/in/sebasrib
    - https://github.com/sebasrib
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
